# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dd5e4c9d7131f5a6e1e59a5833e54a548bdab40217f863ca142b8a0bac496fec301152d27fcf6c3c3ee3e36a7258d2dae8a91cfce9e444411b6f3f5ab8cb0db

test:
  secret_key_base: f8eece08289e72cd439721d3b2cb43a211456e780d4156b4b8b981e501dfd04c3ea51c27b64f48fb073fcae311fdcb9d4a1833faa27f7e49691f644abd9cba20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
